language: python

install:
  pip install -r requirements.txt

script:
  mkdocs build --verbose

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: site
  on:
    branch: master
