site_name: ak1ra Docs
theme:
  # name: 'readthedocs'
  name: 'material'

pages:
    - 'index.md'
    - 'server.md'
    - 'docker.md'
    - 'linux.md'
    - 'terraform.md'
    - 'howtowrite.md'
    - 'docs.md'

extra:
  search:
    language: 'en, ja'
  social:
    - type: github
      link: https://github.com/ak1ra24
    - type: twitter
      link: https://twitter.com/akiranet2580

extra_css:
    - "//fonts.googleapis.com/earlyaccess/notosansjp.css"
    - "//fonts.googleapis.com/css?family=Open+Sans:600,800"
    - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

markdown_extensions:
    - admonition
    - footnotes
    - fontawesome_markdown
    - pymdownx.keys
    - codehilite:
        use_pygments: true
        noclasses: true
        pygments_style: vim
    - pymdownx.details
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.tasklist:
        custom_checkbox: true
